<a href="https://colab.research.google.com/github/bhaskarsanakalaceruvu/github-ass1/blob/main/bhaskar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
                                                                        #NUMPY EXERCISE
#SANAKALACHERUVU BHASKAR 21BCE9177

import numpy as np
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
                                                                  #CREATE AN ARRAY OF 10 ZEROS

ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
                                                                  #Create an array of 10 ones
fives_array = 5 * np.ones(10)
print(fives_array)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [4]:
                                                                 #Create an array of 10 fives
integer_array = np.arange(10, 51)
print(integer_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [5]:
                                                        #Create an array of the integers from 10 to 50
even_integers_array = np.arange(10, 51, 2)
even_integers_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
                                                      #Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
                                                              #Create a 3x3 identity matrix
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
                                                    #Use NumPy to generate a random number between 0 and 1
random_number = np.random.rand()
print(random_number)

0.7796640255698292


In [9]:
                              #Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

random_numbers = np.random.randn(25)
print(random_numbers)


[-0.09065459 -0.37374828  0.42289483 -0.59443028 -0.75595637  0.15942129
 -0.3248282  -0.3885366  -0.1664951   0.51000783  0.32764285  0.95638239
 -0.56114282 -1.04601967 -1.59111595  0.07485567  1.36487537 -0.14625474
  1.08766665 -0.61029722  0.81780591 -0.53872256 -2.10300347  0.60007222
 -0.73044681]


In [10]:
                                                             #Create the following matrix:
matrix = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(matrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [11]:
                                                  #Create an array of 20 linearly spaced points between 0 and 1:
linear_points = np.linspace(0, 1, 20)
print(linear_points)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [12]:
                                                                   #Numpy Indexing and Selection
                                        #Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [13]:
                                                # WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
                                                # BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
                                                # BE ABLE TO SEE THE OUTPUT ANY MORE

submatrix = mat[2:5, 1:5]

print(submatrix)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [14]:
                                              # WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
                                              # BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
                                              # BE ABLE TO SEE THE OUTPUT ANY MORE

value_20 = mat[3, 4]
print(value_20)

20


In [15]:
                                              # WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
                                              # BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
                                              # BE ABLE TO SEE THE OUTPUT ANY MORE

subarray = mat[0:3, 1:2]

print(subarray)

[[ 2]
 [ 7]
 [12]]


In [16]:
                                              # WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
                                              # BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
                                              # BE ABLE TO SEE THE OUTPUT ANY MORE

last_row = mat[-1, :]
print(last_row)

[21 22 23 24 25]


In [17]:
                                              # WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
                                              # BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
                                              # BE ABLE TO SEE THE OUTPUT ANY MORE

desired_subarray = mat[3:5, :]

print(desired_subarray)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
                                                        #Now do the following
                                                        #Get the sum of all the values in mat

total_sum = np.sum(mat)

print(total_sum)

325


In [19]:
                                                    #Get the standard deviation of the values in mat

std_deviation = np.std(mat)

print(std_deviation)

7.211102550927978


In [20]:
                                                        #Get the sum of all the columns in mat


column_sums = np.sum(mat, axis=0)

print(column_sums)

[55 60 65 70 75]
